language: java

install: /bin/true

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  gradle wrapper

before_script:
    - wget https://services.gradle.org/distributions/gradle-4.1-bin.zip
    - unzip gradle-4.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.1
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)